// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "LMSBitLab/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockChapterRepository is an autogenerated mock type for the ChapterRepository type
type MockChapterRepository struct {
	mock.Mock
}

type MockChapterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChapterRepository) EXPECT() *MockChapterRepository_Expecter {
	return &MockChapterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: chapter
func (_m *MockChapterRepository) Create(chapter *model.Chapter) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Chapter) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChapterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - chapter *model.Chapter
func (_e *MockChapterRepository_Expecter) Create(chapter interface{}) *MockChapterRepository_Create_Call {
	return &MockChapterRepository_Create_Call{Call: _e.mock.On("Create", chapter)}
}

func (_c *MockChapterRepository_Create_Call) Run(run func(chapter *model.Chapter)) *MockChapterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Chapter))
	})
	return _c
}

func (_c *MockChapterRepository_Create_Call) Return(_a0 error) *MockChapterRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterRepository_Create_Call) RunAndReturn(run func(*model.Chapter) error) *MockChapterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockChapterRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChapterRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockChapterRepository_Expecter) Delete(id interface{}) *MockChapterRepository_Delete_Call {
	return &MockChapterRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockChapterRepository_Delete_Call) Run(run func(id uint)) *MockChapterRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_Delete_Call) Return(_a0 error) *MockChapterRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockChapterRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByCourseID provides a mock function with given fields: courseID
func (_m *MockChapterRepository) GetAllByCourseID(courseID uint) ([]model.Chapter, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByCourseID")
	}

	var r0 []model.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]model.Chapter, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []model.Chapter); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterRepository_GetAllByCourseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByCourseID'
type MockChapterRepository_GetAllByCourseID_Call struct {
	*mock.Call
}

// GetAllByCourseID is a helper method to define mock.On call
//   - courseID uint
func (_e *MockChapterRepository_Expecter) GetAllByCourseID(courseID interface{}) *MockChapterRepository_GetAllByCourseID_Call {
	return &MockChapterRepository_GetAllByCourseID_Call{Call: _e.mock.On("GetAllByCourseID", courseID)}
}

func (_c *MockChapterRepository_GetAllByCourseID_Call) Run(run func(courseID uint)) *MockChapterRepository_GetAllByCourseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_GetAllByCourseID_Call) Return(_a0 []model.Chapter, _a1 error) *MockChapterRepository_GetAllByCourseID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterRepository_GetAllByCourseID_Call) RunAndReturn(run func(uint) ([]model.Chapter, error)) *MockChapterRepository_GetAllByCourseID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockChapterRepository) GetByID(id uint) (*model.Chapter, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Chapter, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Chapter); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChapterRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockChapterRepository_Expecter) GetByID(id interface{}) *MockChapterRepository_GetByID_Call {
	return &MockChapterRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockChapterRepository_GetByID_Call) Run(run func(id uint)) *MockChapterRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_GetByID_Call) Return(_a0 *model.Chapter, _a1 error) *MockChapterRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterRepository_GetByID_Call) RunAndReturn(run func(uint) (*model.Chapter, error)) *MockChapterRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: chapter
func (_m *MockChapterRepository) Update(chapter *model.Chapter) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Chapter) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChapterRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - chapter *model.Chapter
func (_e *MockChapterRepository_Expecter) Update(chapter interface{}) *MockChapterRepository_Update_Call {
	return &MockChapterRepository_Update_Call{Call: _e.mock.On("Update", chapter)}
}

func (_c *MockChapterRepository_Update_Call) Run(run func(chapter *model.Chapter)) *MockChapterRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Chapter))
	})
	return _c
}

func (_c *MockChapterRepository_Update_Call) Return(_a0 error) *MockChapterRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterRepository_Update_Call) RunAndReturn(run func(*model.Chapter) error) *MockChapterRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChapterRepository creates a new instance of MockChapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChapterRepository {
	mock := &MockChapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
