// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "LMSBitLab/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockCourseRepository is an autogenerated mock type for the CourseRepository type
type MockCourseRepository struct {
	mock.Mock
}

type MockCourseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseRepository) EXPECT() *MockCourseRepository_Expecter {
	return &MockCourseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: course
func (_m *MockCourseRepository) Create(course *model.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCourseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - course *model.Course
func (_e *MockCourseRepository_Expecter) Create(course interface{}) *MockCourseRepository_Create_Call {
	return &MockCourseRepository_Create_Call{Call: _e.mock.On("Create", course)}
}

func (_c *MockCourseRepository_Create_Call) Run(run func(course *model.Course)) *MockCourseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Course))
	})
	return _c
}

func (_c *MockCourseRepository_Create_Call) Return(_a0 error) *MockCourseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseRepository_Create_Call) RunAndReturn(run func(*model.Course) error) *MockCourseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockCourseRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCourseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockCourseRepository_Expecter) Delete(id interface{}) *MockCourseRepository_Delete_Call {
	return &MockCourseRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCourseRepository_Delete_Call) Run(run func(id uint)) *MockCourseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCourseRepository_Delete_Call) Return(_a0 error) *MockCourseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockCourseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockCourseRepository) GetAll() ([]model.Course, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Course
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Course, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Course); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Course)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCourseRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockCourseRepository_Expecter) GetAll() *MockCourseRepository_GetAll_Call {
	return &MockCourseRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockCourseRepository_GetAll_Call) Run(run func()) *MockCourseRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCourseRepository_GetAll_Call) Return(_a0 []model.Course, _a1 error) *MockCourseRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseRepository_GetAll_Call) RunAndReturn(run func() ([]model.Course, error)) *MockCourseRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockCourseRepository) GetByID(id uint) (*model.Course, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Course, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Course); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCourseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCourseRepository_Expecter) GetByID(id interface{}) *MockCourseRepository_GetByID_Call {
	return &MockCourseRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCourseRepository_GetByID_Call) Run(run func(id uint)) *MockCourseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCourseRepository_GetByID_Call) Return(_a0 *model.Course, _a1 error) *MockCourseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseRepository_GetByID_Call) RunAndReturn(run func(uint) (*model.Course, error)) *MockCourseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: course
func (_m *MockCourseRepository) Update(course *model.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCourseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - course *model.Course
func (_e *MockCourseRepository_Expecter) Update(course interface{}) *MockCourseRepository_Update_Call {
	return &MockCourseRepository_Update_Call{Call: _e.mock.On("Update", course)}
}

func (_c *MockCourseRepository_Update_Call) Run(run func(course *model.Course)) *MockCourseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Course))
	})
	return _c
}

func (_c *MockCourseRepository_Update_Call) Return(_a0 error) *MockCourseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseRepository_Update_Call) RunAndReturn(run func(*model.Course) error) *MockCourseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseRepository creates a new instance of MockCourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseRepository {
	mock := &MockCourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
