// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "LMSBitLab/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockLessonRepository is an autogenerated mock type for the LessonRepository type
type MockLessonRepository struct {
	mock.Mock
}

type MockLessonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonRepository) EXPECT() *MockLessonRepository_Expecter {
	return &MockLessonRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: lesson
func (_m *MockLessonRepository) Create(lesson *model.Lesson) error {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Lesson) error); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLessonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - lesson *model.Lesson
func (_e *MockLessonRepository_Expecter) Create(lesson interface{}) *MockLessonRepository_Create_Call {
	return &MockLessonRepository_Create_Call{Call: _e.mock.On("Create", lesson)}
}

func (_c *MockLessonRepository_Create_Call) Run(run func(lesson *model.Lesson)) *MockLessonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Lesson))
	})
	return _c
}

func (_c *MockLessonRepository_Create_Call) Return(_a0 error) *MockLessonRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Create_Call) RunAndReturn(run func(*model.Lesson) error) *MockLessonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockLessonRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLessonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockLessonRepository_Expecter) Delete(id interface{}) *MockLessonRepository_Delete_Call {
	return &MockLessonRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockLessonRepository_Delete_Call) Run(run func(id uint)) *MockLessonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockLessonRepository_Delete_Call) Return(_a0 error) *MockLessonRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockLessonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByChapterID provides a mock function with given fields: id
func (_m *MockLessonRepository) GetAllByChapterID(id uint) ([]model.Lesson, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByChapterID")
	}

	var r0 []model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]model.Lesson, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) []model.Lesson); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetAllByChapterID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByChapterID'
type MockLessonRepository_GetAllByChapterID_Call struct {
	*mock.Call
}

// GetAllByChapterID is a helper method to define mock.On call
//   - id uint
func (_e *MockLessonRepository_Expecter) GetAllByChapterID(id interface{}) *MockLessonRepository_GetAllByChapterID_Call {
	return &MockLessonRepository_GetAllByChapterID_Call{Call: _e.mock.On("GetAllByChapterID", id)}
}

func (_c *MockLessonRepository_GetAllByChapterID_Call) Run(run func(id uint)) *MockLessonRepository_GetAllByChapterID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockLessonRepository_GetAllByChapterID_Call) Return(_a0 []model.Lesson, _a1 error) *MockLessonRepository_GetAllByChapterID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetAllByChapterID_Call) RunAndReturn(run func(uint) ([]model.Lesson, error)) *MockLessonRepository_GetAllByChapterID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockLessonRepository) GetByID(id uint) (*model.Lesson, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Lesson, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Lesson); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockLessonRepository_Expecter) GetByID(id interface{}) *MockLessonRepository_GetByID_Call {
	return &MockLessonRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockLessonRepository_GetByID_Call) Run(run func(id uint)) *MockLessonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) Return(_a0 *model.Lesson, _a1 error) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) RunAndReturn(run func(uint) (*model.Lesson, error)) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: lesson
func (_m *MockLessonRepository) Update(lesson *model.Lesson) error {
	ret := _m.Called(lesson)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Lesson) error); ok {
		r0 = rf(lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - lesson *model.Lesson
func (_e *MockLessonRepository_Expecter) Update(lesson interface{}) *MockLessonRepository_Update_Call {
	return &MockLessonRepository_Update_Call{Call: _e.mock.On("Update", lesson)}
}

func (_c *MockLessonRepository_Update_Call) Run(run func(lesson *model.Lesson)) *MockLessonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Lesson))
	})
	return _c
}

func (_c *MockLessonRepository_Update_Call) Return(_a0 error) *MockLessonRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Update_Call) RunAndReturn(run func(*model.Lesson) error) *MockLessonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLessonRepository creates a new instance of MockLessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonRepository {
	mock := &MockLessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
