// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "LMSBitLab/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockChapterService is an autogenerated mock type for the ChapterService type
type MockChapterService struct {
	mock.Mock
}

type MockChapterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChapterService) EXPECT() *MockChapterService_Expecter {
	return &MockChapterService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockChapterService) Create(input dto.CreateChapterDTO) (dto.ChapterResponseDTO, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.ChapterResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateChapterDTO) (dto.ChapterResponseDTO, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateChapterDTO) dto.ChapterResponseDTO); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(dto.CreateChapterDTO) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChapterService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input dto.CreateChapterDTO
func (_e *MockChapterService_Expecter) Create(input interface{}) *MockChapterService_Create_Call {
	return &MockChapterService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockChapterService_Create_Call) Run(run func(input dto.CreateChapterDTO)) *MockChapterService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.CreateChapterDTO))
	})
	return _c
}

func (_c *MockChapterService_Create_Call) Return(_a0 dto.ChapterResponseDTO, _a1 error) *MockChapterService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_Create_Call) RunAndReturn(run func(dto.CreateChapterDTO) (dto.ChapterResponseDTO, error)) *MockChapterService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockChapterService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChapterService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockChapterService_Expecter) Delete(id interface{}) *MockChapterService_Delete_Call {
	return &MockChapterService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockChapterService_Delete_Call) Run(run func(id uint)) *MockChapterService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockChapterService_Delete_Call) Return(_a0 error) *MockChapterService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterService_Delete_Call) RunAndReturn(run func(uint) error) *MockChapterService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCourseID provides a mock function with given fields: courseID
func (_m *MockChapterService) GetByCourseID(courseID uint) ([]dto.ChapterResponseDTO, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCourseID")
	}

	var r0 []dto.ChapterResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dto.ChapterResponseDTO, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dto.ChapterResponseDTO); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ChapterResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_GetByCourseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCourseID'
type MockChapterService_GetByCourseID_Call struct {
	*mock.Call
}

// GetByCourseID is a helper method to define mock.On call
//   - courseID uint
func (_e *MockChapterService_Expecter) GetByCourseID(courseID interface{}) *MockChapterService_GetByCourseID_Call {
	return &MockChapterService_GetByCourseID_Call{Call: _e.mock.On("GetByCourseID", courseID)}
}

func (_c *MockChapterService_GetByCourseID_Call) Run(run func(courseID uint)) *MockChapterService_GetByCourseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockChapterService_GetByCourseID_Call) Return(_a0 []dto.ChapterResponseDTO, _a1 error) *MockChapterService_GetByCourseID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_GetByCourseID_Call) RunAndReturn(run func(uint) ([]dto.ChapterResponseDTO, error)) *MockChapterService_GetByCourseID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockChapterService) GetByID(id uint) (dto.ChapterResponseDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.ChapterResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (dto.ChapterResponseDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) dto.ChapterResponseDTO); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChapterService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockChapterService_Expecter) GetByID(id interface{}) *MockChapterService_GetByID_Call {
	return &MockChapterService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockChapterService_GetByID_Call) Run(run func(id uint)) *MockChapterService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockChapterService_GetByID_Call) Return(_a0 dto.ChapterResponseDTO, _a1 error) *MockChapterService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_GetByID_Call) RunAndReturn(run func(uint) (dto.ChapterResponseDTO, error)) *MockChapterService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockChapterService) Update(id uint, input dto.UpdateChapterDTO) (dto.ChapterResponseDTO, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.ChapterResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateChapterDTO) (dto.ChapterResponseDTO, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateChapterDTO) dto.ChapterResponseDTO); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint, dto.UpdateChapterDTO) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChapterService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - input dto.UpdateChapterDTO
func (_e *MockChapterService_Expecter) Update(id interface{}, input interface{}) *MockChapterService_Update_Call {
	return &MockChapterService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockChapterService_Update_Call) Run(run func(id uint, input dto.UpdateChapterDTO)) *MockChapterService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(dto.UpdateChapterDTO))
	})
	return _c
}

func (_c *MockChapterService_Update_Call) Return(_a0 dto.ChapterResponseDTO, _a1 error) *MockChapterService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_Update_Call) RunAndReturn(run func(uint, dto.UpdateChapterDTO) (dto.ChapterResponseDTO, error)) *MockChapterService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChapterService creates a new instance of MockChapterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChapterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChapterService {
	mock := &MockChapterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
