// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "LMSBitLab/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockCourseService is an autogenerated mock type for the CourseService type
type MockCourseService struct {
	mock.Mock
}

type MockCourseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseService) EXPECT() *MockCourseService_Expecter {
	return &MockCourseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockCourseService) Create(input dto.CreateCourseDTO) (dto.CourseResponseDTO, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.CourseResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateCourseDTO) (dto.CourseResponseDTO, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateCourseDTO) dto.CourseResponseDTO); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(dto.CourseResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(dto.CreateCourseDTO) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCourseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input dto.CreateCourseDTO
func (_e *MockCourseService_Expecter) Create(input interface{}) *MockCourseService_Create_Call {
	return &MockCourseService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockCourseService_Create_Call) Run(run func(input dto.CreateCourseDTO)) *MockCourseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.CreateCourseDTO))
	})
	return _c
}

func (_c *MockCourseService_Create_Call) Return(_a0 dto.CourseResponseDTO, _a1 error) *MockCourseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_Create_Call) RunAndReturn(run func(dto.CreateCourseDTO) (dto.CourseResponseDTO, error)) *MockCourseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockCourseService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCourseService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockCourseService_Expecter) Delete(id interface{}) *MockCourseService_Delete_Call {
	return &MockCourseService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCourseService_Delete_Call) Run(run func(id uint)) *MockCourseService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCourseService_Delete_Call) Return(_a0 error) *MockCourseService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseService_Delete_Call) RunAndReturn(run func(uint) error) *MockCourseService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockCourseService) GetAll() ([]dto.CourseResponseDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []dto.CourseResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.CourseResponseDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.CourseResponseDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CourseResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCourseService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockCourseService_Expecter) GetAll() *MockCourseService_GetAll_Call {
	return &MockCourseService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockCourseService_GetAll_Call) Run(run func()) *MockCourseService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCourseService_GetAll_Call) Return(_a0 []dto.CourseResponseDTO, _a1 error) *MockCourseService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_GetAll_Call) RunAndReturn(run func() ([]dto.CourseResponseDTO, error)) *MockCourseService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockCourseService) GetByID(id uint) (dto.CourseResponseDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.CourseResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (dto.CourseResponseDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) dto.CourseResponseDTO); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dto.CourseResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCourseService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCourseService_Expecter) GetByID(id interface{}) *MockCourseService_GetByID_Call {
	return &MockCourseService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockCourseService_GetByID_Call) Run(run func(id uint)) *MockCourseService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCourseService_GetByID_Call) Return(_a0 dto.CourseResponseDTO, _a1 error) *MockCourseService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_GetByID_Call) RunAndReturn(run func(uint) (dto.CourseResponseDTO, error)) *MockCourseService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockCourseService) Update(id uint, input dto.UpdateCourseDTO) (dto.CourseResponseDTO, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.CourseResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateCourseDTO) (dto.CourseResponseDTO, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateCourseDTO) dto.CourseResponseDTO); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Get(0).(dto.CourseResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint, dto.UpdateCourseDTO) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCourseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - input dto.UpdateCourseDTO
func (_e *MockCourseService_Expecter) Update(id interface{}, input interface{}) *MockCourseService_Update_Call {
	return &MockCourseService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockCourseService_Update_Call) Run(run func(id uint, input dto.UpdateCourseDTO)) *MockCourseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(dto.UpdateCourseDTO))
	})
	return _c
}

func (_c *MockCourseService_Update_Call) Return(_a0 dto.CourseResponseDTO, _a1 error) *MockCourseService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_Update_Call) RunAndReturn(run func(uint, dto.UpdateCourseDTO) (dto.CourseResponseDTO, error)) *MockCourseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseService creates a new instance of MockCourseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseService {
	mock := &MockCourseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
