// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "LMSBitLab/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockLessonService is an autogenerated mock type for the LessonService type
type MockLessonService struct {
	mock.Mock
}

type MockLessonService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonService) EXPECT() *MockLessonService_Expecter {
	return &MockLessonService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: input
func (_m *MockLessonService) Create(input dto.CreateLessonDTO) (dto.LessonResponseDTO, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.LessonResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateLessonDTO) (dto.LessonResponseDTO, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateLessonDTO) dto.LessonResponseDTO); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(dto.LessonResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(dto.CreateLessonDTO) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLessonService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - input dto.CreateLessonDTO
func (_e *MockLessonService_Expecter) Create(input interface{}) *MockLessonService_Create_Call {
	return &MockLessonService_Create_Call{Call: _e.mock.On("Create", input)}
}

func (_c *MockLessonService_Create_Call) Run(run func(input dto.CreateLessonDTO)) *MockLessonService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.CreateLessonDTO))
	})
	return _c
}

func (_c *MockLessonService_Create_Call) Return(_a0 dto.LessonResponseDTO, _a1 error) *MockLessonService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_Create_Call) RunAndReturn(run func(dto.CreateLessonDTO) (dto.LessonResponseDTO, error)) *MockLessonService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockLessonService) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLessonService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockLessonService_Expecter) Delete(id interface{}) *MockLessonService_Delete_Call {
	return &MockLessonService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockLessonService_Delete_Call) Run(run func(id uint)) *MockLessonService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockLessonService_Delete_Call) Return(_a0 error) *MockLessonService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonService_Delete_Call) RunAndReturn(run func(uint) error) *MockLessonService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChapterID provides a mock function with given fields: chapterID
func (_m *MockLessonService) GetByChapterID(chapterID uint) ([]dto.LessonResponseDTO, error) {
	ret := _m.Called(chapterID)

	if len(ret) == 0 {
		panic("no return value specified for GetByChapterID")
	}

	var r0 []dto.LessonResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dto.LessonResponseDTO, error)); ok {
		return rf(chapterID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dto.LessonResponseDTO); ok {
		r0 = rf(chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.LessonResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_GetByChapterID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChapterID'
type MockLessonService_GetByChapterID_Call struct {
	*mock.Call
}

// GetByChapterID is a helper method to define mock.On call
//   - chapterID uint
func (_e *MockLessonService_Expecter) GetByChapterID(chapterID interface{}) *MockLessonService_GetByChapterID_Call {
	return &MockLessonService_GetByChapterID_Call{Call: _e.mock.On("GetByChapterID", chapterID)}
}

func (_c *MockLessonService_GetByChapterID_Call) Run(run func(chapterID uint)) *MockLessonService_GetByChapterID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockLessonService_GetByChapterID_Call) Return(_a0 []dto.LessonResponseDTO, _a1 error) *MockLessonService_GetByChapterID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_GetByChapterID_Call) RunAndReturn(run func(uint) ([]dto.LessonResponseDTO, error)) *MockLessonService_GetByChapterID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockLessonService) GetByID(id uint) (dto.LessonResponseDTO, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.LessonResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (dto.LessonResponseDTO, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) dto.LessonResponseDTO); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(dto.LessonResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockLessonService_Expecter) GetByID(id interface{}) *MockLessonService_GetByID_Call {
	return &MockLessonService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockLessonService_GetByID_Call) Run(run func(id uint)) *MockLessonService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockLessonService_GetByID_Call) Return(_a0 dto.LessonResponseDTO, _a1 error) *MockLessonService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_GetByID_Call) RunAndReturn(run func(uint) (dto.LessonResponseDTO, error)) *MockLessonService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, input
func (_m *MockLessonService) Update(id uint, input dto.UpdateLessonDTO) (dto.LessonResponseDTO, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.LessonResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateLessonDTO) (dto.LessonResponseDTO, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(uint, dto.UpdateLessonDTO) dto.LessonResponseDTO); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Get(0).(dto.LessonResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(uint, dto.UpdateLessonDTO) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint
//   - input dto.UpdateLessonDTO
func (_e *MockLessonService_Expecter) Update(id interface{}, input interface{}) *MockLessonService_Update_Call {
	return &MockLessonService_Update_Call{Call: _e.mock.On("Update", id, input)}
}

func (_c *MockLessonService_Update_Call) Run(run func(id uint, input dto.UpdateLessonDTO)) *MockLessonService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(dto.UpdateLessonDTO))
	})
	return _c
}

func (_c *MockLessonService_Update_Call) Return(_a0 dto.LessonResponseDTO, _a1 error) *MockLessonService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_Update_Call) RunAndReturn(run func(uint, dto.UpdateLessonDTO) (dto.LessonResponseDTO, error)) *MockLessonService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLessonService creates a new instance of MockLessonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonService {
	mock := &MockLessonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
